// GENERATED by tools/port_to_wasm.py — do not edit.
package com.pixelclassics.app

object R {
    object string {
        const val app_name: Int = 0
        const val nc_left_footer: Int = 1
        const val nc_right_footer: Int = 2
        const val about_title: Int = 3
        const val about_subtitle: Int = 4
        const val about_author_label: Int = 5
        const val about_author_value: Int = 6
        const val about_version_label: Int = 7
        const val about_games_label: Int = 8
        const val about_license_label: Int = 9
        const val about_thanks: Int = 10
        const val about_disclaimer: Int = 11
        const val settings_title: Int = 12
        const val settings_language: Int = 13
        const val settings_sound: Int = 14
        const val settings_haptic: Int = 15
        const val settings_music: Int = 16
        const val dialog_close: Int = 17
        const val game_snake: Int = 18
        const val game_pong: Int = 19
        const val game_arkanoid: Int = 20
        const val game_tetris: Int = 21
        const val game_jungle_run: Int = 22
        const val game_naval: Int = 23
        const val game_missile: Int = 24
        const val game_rogue: Int = 25
        const val game_et: Int = 26
        const val game_exodus: Int = 27
        const val game_digger: Int = 28
        const val game_frogger: Int = 29
        const val game_minesweeper: Int = 30
        const val game_paratrooper: Int = 31
        const val game_river_raid: Int = 32
        const val game_battle_city: Int = 33
        const val game_lunar: Int = 34
        const val game_asteroids: Int = 35
        const val game_pushbox: Int = 36
        const val game_muncher: Int = 37
        const val game_pitfall_classic: Int = 38
        const val game_star_wing: Int = 39
        const val game_cave: Int = 40
        const val game_tic_tac_toe: Int = 41
        const val game_saloon: Int = 42
        const val game_tower_climb: Int = 43
        const val game_super_barsik: Int = 44
        const val game_f21: Int = 45
    }
}

object StringTable {
    val en: Array<String> = arrayOf(
        "The Pixel Campfire",
        "GAMES: %1\$d",
        "C:\\\\ 14 files, 640K free",
        "A B O U T",
        "Playable stories from game history.",
        "Author:",
        "LISOVSKII EVGENII",
        "Version:",
        "Games:",
        "License:",
        "Thank you for playing The Pixel Campfire.\nIf you enjoy the games — leave a rating, it helps a lot.",
        "All games here are original, nostalgic and educational re-imaginings of classic arcade mechanics. Game mechanics are not copyrightable; all trademarks, names and franchises belong to their respective owners. We claim no affiliation with or endorsement by them. If you are a rights-holder with any concern, write to elyssov@gmail.com and we will resolve it promptly.",
        "S E T T I N G S",
        "Language",
        "Sound",
        "Haptic",
        "Music",
        "Close",
        "Snake",
        "Paddles",
        "Brick Buster",
        "Brix",
        "Jungle Run",
        "Naval Battle",
        "Missile Defense",
        "Dungeon",
        "ExTer",
        "Exodus",
        "Tunneler",
        "Road Hopper",
        "Mines",
        "Paratrooper",
        "River Run",
        "Steel Frontier",
        "Moon Lander",
        "Rock Storm",
        "Pushbox",
        "Muncher",
        "Pit Jumper",
        "Star Swarm",
        "Cave Quest",
        "Tic-Tac-Toe",
        "Saloon",
        "Iron Climb",
        "Super Барсик Bros.",
        "F-21 Ferret",
    )
    val ru: Array<String> = arrayOf(
        "Пиксельный костёр",
        "ИГРЫ: %1\$d",
        "C:\\\\ 14 файлов, 640К свободно",
        "О П Р О Г Р А М М Е",
        "Игровые истории, в которые можно сыграть.",
        "Автор:",
        "ЛИСОВСКИЙ ЕВГЕНИЙ",
        "Версия:",
        "Игр:",
        "Лицензия:",
        "Спасибо, что играешь в «Пиксельный костёр».\nОценка в Play Store очень помогает — заранее благодарю.",
        "Все игры здесь — оригинальные, ностальгические и образовательные переосмысления классических аркадных механик. Игровые механики не охраняются авторским правом; все товарные знаки, названия и франшизы принадлежат их владельцам. Мы не заявляем ни о какой связи с ними или их одобрении. Если вы правообладатель и у вас есть вопросы — напишите на elyssov@gmail.com, и мы всё уладим оперативно.",
        "Н А С Т Р О Й К И",
        "Язык",
        "Звук",
        "Вибрация",
        "Музыка",
        "Закрыть",
        "Змейка",
        "Paddles",
        "Brick Buster",
        "Брикс",
        "Джангл-Ран",
        "Морской бой",
        "Missile Defense",
        "Dungeon",
        "ExTer",
        "Исход",
        "Tunneler",
        "Road Hopper",
        "Mines",
        "Десантник",
        "River Run",
        "Steel Frontier",
        "Moon Lander",
        "Rock Storm",
        "Толкач",
        "Хомяк",
        "Pit Jumper",
        "Star Swarm",
        "Cave Quest",
        "Крестики-нолики",
        "Салун",
        "Iron Climb",
        "Super Барсик Bros.",
        "F-21 «Хорёк»",
    )
    val vi: Array<String> = arrayOf(
        "Đốm lửa Pixel",
        "TRÒ CHƠI: %1\$d",
        "C:\\\\ 14 tệp, 640K trống",
        "G I Ớ I   T H I Ệ U",
        "Những câu chuyện game bạn có thể chơi.",
        "Tác giả:",
        "LISOVSKII EVGENII",
        "Phiên bản:",
        "Trò chơi:",
        "Giấy phép:",
        "Cảm ơn bạn đã chơi Đốm lửa Pixel.\nNếu thích — hãy đánh giá trên Play Store, điều này rất quý giá.",
        "Tất cả trò chơi ở đây là bản tái hiện nguyên gốc, mang tính hoài niệm và giáo dục về các cơ chế arcade kinh điển. Cơ chế trò chơi không thuộc bản quyền; mọi thương hiệu, tên gọi và nhượng quyền đều thuộc về chủ sở hữu tương ứng. Chúng tôi không tuyên bố có liên kết hay được họ chứng thực. Nếu bạn là chủ sở hữu quyền và có thắc mắc, hãy viết thư đến elyssov@gmail.com, chúng tôi sẽ giải quyết nhanh chóng.",
        "C À I   Đ Ặ T",
        "Ngôn ngữ",
        "Âm thanh",
        "Rung",
        "Nhạc",
        "Đóng",
        "Rắn săn mồi",
        "Paddles",
        "Brick Buster",
        "Brix",
        "Chạy Rừng",
        "Hải chiến",
        "Missile Defense",
        "Dungeon",
        "ExTer",
        "Xuất hành",
        "Tunneler",
        "Road Hopper",
        "Mines",
        "Lính dù",
        "River Run",
        "Steel Frontier",
        "Moon Lander",
        "Rock Storm",
        "Đẩy hộp",
        "Người ăn",
        "Pit Jumper",
        "Star Swarm",
        "Cave Quest",
        "Caro nhỏ",
        "Saloon",
        "Iron Climb",
        "Super Барсик Bros.",
        "F-21 Ferret",
    )

    fun lookup(lang: String, id: Int): String = when (lang) {
        "ru" -> ru[id]
        "vi" -> vi[id]
        else -> en[id]
    }
}
